/* Body file for function bridge_a
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "bridge_a.h"
//#include <stdio.h>

static volatile int bridge_sent_count = 0;

void bridge_a_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[bridge_a] Startup");
}

void bridge_a_PI_send_pdu
      (const asn1SccCFDP_DATA *IN_pdu_data,
       asn1SccCFDP_BOOLEAN *OUT_result)

{
    bridge_a_RI_send(IN_pdu_data);
    ++bridge_sent_count;

    *OUT_result = true;
}

