/* Body file for function bridge
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "bridge.h"
//#include <stdio.h>


static volatile int bridge_received_count = 0;
static volatile int bridge_processed_count = 0;

void bridge_startup(void)
{
}

void bridge_PI_can_send
      (asn1SccCFDP_BOOLEAN *OUT_result)

{
     *OUT_result = true;
}

void bridge_PI_timer_restart
      (const asn1SccCFDP_TIMEOUT *IN_timeout,
       asn1SccCFDP_BOOLEAN *OUT_result)

{
    *OUT_result = true;
}


void bridge_PI_timer_stop
      (asn1SccCFDP_BOOLEAN *OUT_result)

{
    *OUT_result = true;
}


void bridge_PI_receive( const asn1SccCFDP_DATA *IN_param)
{
    ++bridge_received_count;
    bridge_RI_received_pdu(IN_param);
    ++bridge_processed_count;
}
