/* Body file for function taste_env
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "taste_env.h"
//#include <stdio.h>


void taste_env_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[taste_env] Startup");
}

void taste_env_PI_calculate_checksum
      (const asn1SccGAMMA_FILE_PATH *IN_file_path,
       const asn1SccGAMMA_CFDP_CHECKSUM_TYPE *IN_checksum_type,
       asn1SccGAMMA_CFDP_CHECKSUM *OUT_checksum)

{
   // Write your code here
}


void taste_env_PI_error_callback
      (const asn1SccGAMMA_CFDP_ERROR_TYPE *IN_error_type,
       const asn1SccGAMMA_CFDP_ERROR_CODE *IN_error_code)

{
   // Write your code here
}


void taste_env_PI_get_file_size
      (asn1SccGAMMA_CFDP_SIZE *OUT_size)

{
   // Write your code here
}


void taste_env_PI_indication_callback
      (const asn1SccGAMMA_CFDP_INDICATION_TYPE *IN_indication_type,
       const asn1SccGAMMA_CFDP_TRANSACTION_ID *IN_transaction_id)

{
   // Write your code here
}


void taste_env_PI_is_ready
      (asn1SccGAMMA_BOOLEAN *OUT_result)

{
   // Write your code here
}


void taste_env_PI_read_file
      (const asn1SccGAMMA_FILE_PATH *IN_file_path,
       const asn1SccGAMMA_CFDP_OFFSET *IN_offset,
       asn1SccGAMMA_CFDP_DATA *OUT_read_data,
       const asn1SccGAMMA_CFDP_SIZE *IN_size)

{
   // Write your code here
}


void taste_env_PI_send_pdu
      (const asn1SccGAMMA_CFDP_DATA *IN_pdu_data)

{
   // Write your code here
}


void taste_env_PI_write_file
      (const asn1SccGAMMA_FILE_PATH *IN_file_path,
       const asn1SccGAMMA_CFDP_OFFSET *IN_offset,
       const asn1SccGAMMA_CFDP_DATA *IN_write_data,
       const asn1SccGAMMA_CFDP_SIZE *IN_size)

{
   // Write your code here
}


