/* Header file for function cfdp
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void cfdp_startup(void);

/* Provided interfaces */
void cfdp_PI_can_send_callback( void );


void cfdp_PI_cfdp_close( void );


void cfdp_PI_cfdp_copy_operation_id_already_allocated( const asn1SccGAMMA_OPERATION_ID *, asn1SccGAMMA_BOOLEAN * );


void cfdp_PI_cfdp_init( const asn1SccGAMMA_CFDP_ENTITY_ID *, const asn1SccGAMMA_CFDP_CHECKSUM_TYPE *, const asn1SccGAMMA_CFDP_INACTIVITY_TIMEOUT * );


void cfdp_PI_cfdp_request_copy_file_operation( const asn1SccGAMMA_OPERATION_ID *, const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_CFDP_ENTITY_ID *, const asn1SccGAMMA_FILE_PATH * );


void cfdp_PI_received_pdu( const asn1SccGAMMA_CFDP_DATA * );

/* Required interfaces */
extern void cfdp_RI_can_send( asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_cfdp_copy_file_operation_respond( const asn1SccGAMMA_OPERATION_ID *, asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_error_callback( const asn1SccGAMMA_CFDP_ERROR_TYPE *, const asn1SccGAMMA_CFDP_ERROR_CODE * );


extern void cfdp_RI_get_file_size( const asn1SccGAMMA_FILE_PATH *, asn1SccGAMMA_CFDP_SIZE * );


extern void cfdp_RI_indication_callback( const asn1SccGAMMA_CFDP_INDICATION_TYPE *, const asn1SccGAMMA_CFDP_TRANSACTION_ID * );


extern void cfdp_RI_list_directory( const asn1SccGAMMA_FILE_PATH *, asn1SccGAMMA_CFDP_DATA *, asn1SccGAMMA_CFDP_SIZE *, asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_read_file( const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_CFDP_OFFSET *, asn1SccGAMMA_CFDP_DATA *, const asn1SccGAMMA_CFDP_SIZE *, asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_send_pdu( const asn1SccGAMMA_CFDP_DATA *, asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_timer_restart( const asn1SccGAMMA_CFDP_INACTIVITY_TIMEOUT *, asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_timer_stop( asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_write_file( const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_CFDP_OFFSET *, const asn1SccGAMMA_CFDP_DATA *, const asn1SccGAMMA_CFDP_SIZE *, asn1SccGAMMA_BOOLEAN * );


#ifdef __cplusplus
}
#endif
