/* Header file for function cfdp
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void cfdp_startup(void);

/* Provided interfaces */
void cfdp_PI_file_handling_copy_operation_id_alredy_allocated( const asn1SccGAMMA_OPERATION_ID *, asn1SccGAMMA_BOOLEAN * );


void cfdp_PI_file_handling_is_object_path_remote( const asn1SccGAMMA_FILE_PATH *, asn1SccGAMMA_BOOLEAN * );


void cfdp_PI_file_handling_is_object_path_valid( const asn1SccGAMMA_FILE_PATH *, asn1SccGAMMA_BOOLEAN * );


void cfdp_PI_file_handling_request_copy_file_operation( const asn1SccGAMMA_OPERATION_ID *, const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_FILE_PATH *, const asn1SccROOT_REQUEST_ID *, const asn1SccROOT_TC_SECONDARY_HEADER * );


void cfdp_PI_init( void );

/* Required interfaces */
extern void cfdp_RI_calculate_checksum( const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_CFDP_CHECKSUM_TYPE *, asn1SccGAMMA_CFDP_CHECKSUM * );


extern void cfdp_RI_error_callback( const asn1SccGAMMA_CFDP_ERROR_TYPE *, const asn1SccGAMMA_CFDP_ERROR_CODE * );


extern void cfdp_RI_file_handling_copy_file_operation_respond( const asn1SccGAMMA_OPERATION_ID *, const asn1SccROOT_REQUEST_ID *, const asn1SccROOT_TC_SECONDARY_HEADER *, asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_get_file_size( const asn1SccGAMMA_FILE_PATH *, asn1SccGAMMA_CFDP_SIZE * );


extern void cfdp_RI_indication_callback( const asn1SccGAMMA_CFDP_INDICATION_TYPE *, const asn1SccGAMMA_CFDP_TRANSACTION_ID * );


extern void cfdp_RI_is_ready( asn1SccGAMMA_BOOLEAN * );


extern void cfdp_RI_read_file( const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_CFDP_OFFSET *, asn1SccGAMMA_CFDP_DATA *, const asn1SccGAMMA_CFDP_SIZE * );


extern void cfdp_RI_send_pdu( const asn1SccGAMMA_CFDP_DATA * );


extern void cfdp_RI_write_file( const asn1SccGAMMA_FILE_PATH *, const asn1SccGAMMA_CFDP_OFFSET *, const asn1SccGAMMA_CFDP_DATA *, const asn1SccGAMMA_CFDP_SIZE * );


#ifdef __cplusplus
}
#endif
