#include "constants.h"

// Map Condition Codes to Default Fault Handler Actions
const enum FaultHandlerAction DEFAULT_FAULT_HANDLER_ACTIONS [16] = {
	FAULT_HANDLER_IGNORE,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_IGNORE,
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_CANCEL,
};