#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "cfdp_dataview.h"

enum MachineState {
	SEND_METADATA,
	SEND_FILE,
	SEND_EOF,
	TRANSACTION_CANCELLED,
	WAIT_FOR_MD,
	WAIT_FOR_EOF,
	GET_MISSING_DATA,
	SEND_FINISHED,
	COMPLETED
};

enum FaultHandlerAction {
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_SUSPEND,
	FAULT_HANDLER_IGNORE,
	FAULT_HANDLER_ABANDON
};

enum IndicationType {
	TRANSACTION_INDICATION,
	EOF_SENT_INDICATION,
	FINISHED_INDICATION,
	REPORT_INDICATION,
	EOF_RECEIVED_INDICATION,
	METADATA_RECEIVED_INDICATION,
	FILESEGMENT_RECEIVED_INDICATION,
	ABANDONED_INDICATION,
	SUSPENDED_INDICATION,
	RESUMED_INDICATION,
	FAULT_INDICATION,
	SUCCESSFUL_LISTING_INDICATION,
	UNSUCCESSFUL_LISTING_INDICATION
};

enum ChecksumType { CHECKSUM_TYPE_MODULAR = 0, CHECKSUM_TYPE_NONE = 15 };

enum ErrorType {
	ASN1SCC_ERROR,
	UNSUPPORTED_ACTION,
	SEGMENTATION_ERROR,
	FILESTORE_ERROR,
	TRANSPORT_ERROR,
	TIMER_ERROR
};

#define DIRECTIVE_CODE_EOF 0x04
#define DIRECTIVE_CODE_FINISHED 0x05

#define MAX_FILE_NAME_SIZE (cfdpFileName_REQUIRED_BYTES_FOR_ACN_ENCODING - 1)
#define MAX_LISTING_FILE_NAME_SIZE                                             \
	(cfdpListingFileName_REQUIRED_BYTES_FOR_ACN_ENCODING - 1)
#define MAX_NUMBER_OF_SENDER_MACHINES 1
#define MAX_NUMBER_OF_RECEIVER_MACHINES 1

// two messages are a necessery minimum for handling of file listing
#define MAX_NUMBER_OF_MESSAGES_TO_USER 2

#define CFDP_ALIGNMENT_SIZE 8
#define CFDP_ALIGNED __attribute__((aligned(CFDP_ALIGNMENT_SIZE)))
#define CFDP_ALIGN(size)                                                       \
	(((size + (CFDP_ALIGNMENT_SIZE - 1)) / CFDP_ALIGNMENT_SIZE) *          \
	 CFDP_ALIGNMENT_SIZE)

#define CFDP_BUFFER_SIZE(item_size) (CFDP_ALIGN(item_size))

#define VIRTUAL_SOURCE_FILE_BUFFER_SIZE CFDP_BUFFER_SIZE(1024)
#define FILE_SEGMENT_BUFFER_SIZE                                               \
	CFDP_BUFFER_SIZE(cfdpFileData_REQUIRED_BYTES_FOR_ACN_ENCODING - 2)
#define PDU_BUFFER_SIZE                                                        \
	CFDP_BUFFER_SIZE(cfdpCfdpPDU_REQUIRED_BYTES_FOR_ACN_ENCODING +         \
			 (MAX_NUMBER_OF_MESSAGES_TO_USER *                     \
			  cfdpTLV_REQUIRED_BYTES_FOR_ACN_ENCODING))

#define VIRTUAL_SOURCE_FILE_BUFFER_OFFSET 0
#define FILE_SEGMENT_BUFFER_OFFSET (VIRTUAL_SOURCE_FILE_BUFFER_SIZE)
#define PDU_BUFFER_OFFSET                                                      \
	(FILE_SEGMENT_BUFFER_OFFSET + FILE_SEGMENT_BUFFER_SIZE)
#define MODIFIED_PDU_BUFFER_OFFSET (PDU_BUFFER_OFFSET + PDU_BUFFER_SIZE)
#define TYPED_PDU_BUFFER_SIZE PDU_BUFFER_SIZE
#define EVENT_BUFFER_SIZE CFDP_BUFFER_SIZE(1024)
#define TYPED_PDU_BUFFER_OFFSET                                                \
	(MODIFIED_PDU_BUFFER_OFFSET + PDU_BUFFER_SIZE)
#define EVENT_BUFFER_OFFSET                                                    \
	(TYPED_PDU_BUFFER_OFFSET + TYPED_PDU_BUFFER_SIZE)

#define CFDP_DATA_BUFFER_SIZE                                                  \
	(VIRTUAL_SOURCE_FILE_BUFFER_SIZE + FILE_SEGMENT_BUFFER_SIZE +          \
	 3 * PDU_BUFFER_SIZE + EVENT_BUFFER_SIZE)
#define CFDP_DATA_BUFFER(name) uint8_t name[CFDP_DATA_BUFFER_SIZE] CFDP_ALIGNED

extern const char VIRTUAL_LISTING_FILENAME[9];

extern const enum FaultHandlerAction DEFAULT_FAULT_HANDLER_ACTIONS[16];

#endif
