/* Body file for function FileSystemProxy
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "filesystemproxy.h"
#include <string.h>
//#include <stdio.h>

void filesystemproxy_startup(void)
{
}

void filesystemproxy_PI_get_file_size
      (const asn1SccCFDP_FILE_PATH *IN_filepath,
       asn1SccCFDP_SIZE *OUT_size)
{
    asn1SccLITTLE_FS_REPOSITORY_PATH path;
    strncpy(path.field_data, IN_filepath->field_data, 9);
    asn1SccLITTLE_FS_MEMORY_OFFSET size = 0;
    asn1SccLITTLE_FS_BOOLEAN result = false;
    filesystemproxy_RI_get_file_size(&path, &size, &result);
    if(!result) {
        *OUT_size = 0;
    }
    else {
        *OUT_size = size;
    }
}
static asn1SccCFDP_DATA *listing_data = NULL;
static asn1SccCFDP_SIZE *listing_size = NULL;
static bool listing_success = false;

void filesystemproxy_PI_list_directory
      (const asn1SccCFDP_FILE_PATH *IN_dir_path,
       asn1SccCFDP_DATA *OUT_listing_data,
       asn1SccCFDP_SIZE *OUT_listing_size,
       asn1SccCFDP_BOOLEAN *OUT_result)
{
    /*OUT_listing_data->field_data.nCount = 0;
    OUT_listing_data->field_data.arr[0] = '\0';
    *OUT_listing_size = 0;
    *OUT_result = true; */
    asn1SccLITTLE_FS_REPOSITORY_PATH path;
    strncpy(path.field_data, IN_dir_path->field_data, 9);
    listing_data = OUT_listing_data;
    listing_size = OUT_listing_size;
    *listing_size = 0;
    listing_success = false;
    filesystemproxy_RI_report_content_of_repository_request(&path);
    *OUT_result = listing_success;
}

void filesystemproxy_PI_report_content_of_repository_request_respond( const asn1SccLITTLE_FS_REPOSITORY_PATH *IN_repository_path, asn1SccLITTLE_FS_REPOSITORY_OBJECTS * OUT_files)
{
    listing_data->field_data.arr[0] = '\0';
    listing_data->field_data.nCount = 0;
    for(int i = 0; i < OUT_files->field_data.nCount; ++i)
    {
        size_t object_name_size = strlen(OUT_files->field_data.arr[i].object_name.field_data);
        if(listing_data->field_data.nCount + object_name_size + 1 >= 512) {
            return;
        }
        strncat(listing_data->field_data.arr, OUT_files->field_data.arr[i].object_name.field_data, 9);
        strncat(listing_data->field_data.arr, "\n", 1);
        listing_data->field_data.nCount += object_name_size + 1;
        listing_size += object_name_size + 1;
    }

    listing_success = true;
}

void filesystemproxy_PI_read_file
      (const asn1SccCFDP_FILE_PATH *IN_file_path,
       const asn1SccCFDP_OFFSET *IN_offset,
       asn1SccCFDP_DATA *OUT_read_data,
       const asn1SccCFDP_SIZE *IN_size,
       asn1SccCFDP_BOOLEAN *OUT_result)
{
    /* OUT_read_data->field_data.nCount = *IN_size;
    *OUT_result = true; */

    asn1SccLITTLE_FS_REPOSITORY_PATH path;
    strncpy(path.field_data, IN_file_path->field_data, 9);
    asn1SccLITTLE_FS_MEMORY_OFFSET offset = *IN_offset;
    asn1SccLITTLE_FS_MEMORY_OFFSET size = *IN_size;
    asn1SccLITTLE_FS_MEMORY_DATA data;
    asn1SccLITTLE_FS_BOOLEAN result = false;

    filesystemproxy_RI_read_file(&path, &offset, &size, &data, &result);
    if(result == false) {
        *OUT_result = false;
        return;
    }
    OUT_read_data->field_data.nCount = data.field_data.nCount;
    memcpy(OUT_read_data->field_data.arr, data.field_data.arr, data.field_data.nCount);
    *OUT_result = true;

}

void filesystemproxy_PI_write_file
      (const asn1SccCFDP_FILE_PATH *IN_file_path,
       const asn1SccCFDP_OFFSET *IN_offset,
       const asn1SccCFDP_DATA *IN_write_data,
       const asn1SccCFDP_SIZE *IN_size,
       asn1SccCFDP_BOOLEAN *OUT_result)
{
    //*OUT_result = true;

    if(*IN_size != IN_write_data->field_data.nCount) {
        *OUT_result = false;
    }
    static asn1SccLITTLE_FS_REPOSITORY_PATH path;
    strncpy(path.field_data, IN_file_path->field_data, 9);

    asn1SccLITTLE_FS_MAXIMUM_SIZE maximum_size = 0;
    asn1SccLITTLE_FS_ADDITIONAL_FILE_ATTRIBUTE file_attr;
    file_attr.field_data.nCount = 1;
    file_attr.field_data.arr[0] = 0xab;
    asn1SccLITTLE_FS_BOOLEAN result = false;
    filesystemproxy_RI_file_handling_create_file(&path, &maximum_size,
                                                 &file_attr, &result);

    asn1SccLITTLE_FS_MEMORY_OFFSET offset = *IN_offset;
    asn1SccLITTLE_FS_MEMORY_DATA data;
    memcpy(data.field_data.arr, IN_write_data->field_data.arr, IN_write_data->field_data.nCount);
    data.field_data.nCount = IN_write_data->field_data.nCount;
    result = false;

    filesystemproxy_RI_write_to_file(&path, &offset,&data, &result);

    *OUT_result = result;
}
