/* Body file for function bridge_c
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "bridge_c.h"
//#include <stdio.h>


void bridge_c_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[bridge_c] Startup");
}

void bridge_c_PI_indication_callback
      (const asn1SccCFDP_INDICATION_TYPE *IN_indication_type,
       const asn1SccCFDP_TRANSACTION_ID *IN_transaction_id)

{
    asn1SccIndication_Info i;
    i.ind_type = *IN_indication_type;
    i.trans_id = *IN_transaction_id;
    bridge_c_RI_indication(&i);
}
