/* Body file for function computer
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "computer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <pthread.h>

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#define PORT 5111
#define RECEIVER_PORT 5222
#define BUFFER_SIZE 8192

static const char IP_ADDRESS[] = "127.0.0.1";
static int sockfd = 0;
static pthread_t listen_thread_id = 0;

static void* listen_thread(void*)
{
    uint8_t buffer[BUFFER_SIZE];
    struct sockaddr_in source;
    memset(&source, 0, sizeof(struct sockaddr_in));
    socklen_t source_len = sizeof(struct sockaddr_in);

    bool error_occurred = false;
    printf("Listen thread started\n");
    while(!error_occurred) {
        ssize_t result = recvfrom(sockfd, buffer, BUFFER_SIZE - 1, 0, (struct sockaddr*)&source, &source_len);
        if(result < 0) {
            error_occurred = true;
            fprintf(stderr, "Error occurred while receiving data. Stopping listen thread.\n");
        }
        else {
            buffer[result] = '\0';
            asn1SccCFDP_DATA pdu_data;
            memcpy(pdu_data.field_data.arr, buffer, result);
            pdu_data.field_data.nCount = result;

            printf("Computer -> SamV71 :: %ld bytes\n", result);
            computer_RI_receive(&pdu_data);
        }
    }

    return NULL;
}

void computer_startup(void)
{
    sockfd = socket(AF_INET, SOCK_DGRAM, 0);
    if(sockfd < 0) {
        fprintf(stderr, "Cannot create socket: %s\n", strerror(errno));
        exit(EXIT_FAILURE);
    }

    struct sockaddr_in server_addr;
    memset(&server_addr, 0, sizeof(server_addr));

    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = inet_addr(IP_ADDRESS);
    server_addr.sin_port = htons(PORT);

    if(bind(sockfd, (struct sockaddr*)&server_addr, sizeof(struct sockaddr_in)) < 0) {
        fprintf(stderr, "Cannot bind socket to %s:%u: %s\n", IP_ADDRESS, PORT, strerror(errno));
        exit(EXIT_FAILURE);
    }

    int result = pthread_create(&listen_thread_id, NULL, &listen_thread, NULL);

    if(result != 0) {
        if(result == EAGAIN) {
            fprintf(stderr, "Insufficient resources to create another thread.\n");
        }
        else if(result == EINVAL) {
            fprintf(stderr, "Invalid settings in attr.\n");
        }
        else if(result == EPERM) {
            fprintf(stderr, "No permission to set the scheduling policy and parameters speci‐fied in attr.\n");
        }
        else {
            fprintf(stderr, "Unable to start thread, unknown error %d\n", result);
        }
        exit(EXIT_FAILURE);
    }
}

void computer_PI_send
      (const asn1SccCFDP_DATA *IN_param)

{
    struct sockaddr_in target;
    memset(&target, 0, sizeof(struct sockaddr_in));
    target.sin_family = AF_INET;
    target.sin_port = htons(RECEIVER_PORT);
    target.sin_addr.s_addr = inet_addr(IP_ADDRESS);

    printf("SamV71 -> Computer :: %u bytes\n", IN_param->field_data.nCount);
    ssize_t result = sendto(sockfd, IN_param->field_data.arr, IN_param->field_data.nCount, 0, (struct sockaddr*)&target, sizeof(struct sockaddr_in));
    if(result < 0) {
        fprintf(stderr, "Unable to send data: %s\n", strerror(errno));
    }
    if(result != IN_param->field_data.nCount) {
        fprintf(stderr, "Incomplete send, only %ld bytes were transferred\n", result);
    }
}

void computer_PI_err( const asn1SccError_Info * IN_p1)
{
    printf("SamV71 reported error: type=%lu, code=%lu\n", IN_p1->err_type, IN_p1->err_code);
}


void computer_PI_indication( const asn1SccIndication_Info *IN_p1 )
{
    printf("SamV71 reported indication: type=%lu, trans_id={%lu, %lu}\n", IN_p1->ind_type, IN_p1->trans_id.source_entity_id, IN_p1->trans_id.seq_number);
}


