/* Header file for function cfdp
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void cfdp_startup(void);

/* Provided interfaces */
void cfdp_PI_can_send_callback( void );


void cfdp_PI_cfdp_close( void );


void cfdp_PI_cfdp_copy_operation_id_already_allocated( const asn1SccCFDP_OPERATION_ID *, asn1SccCFDP_BOOLEAN * );


void cfdp_PI_cfdp_init( const asn1SccCFDP_ENTITY_ID *, const asn1SccCFDP_CHECKSUM_TYPE *, const asn1SccCFDP_INACTIVITY_TIMEOUT * );


void cfdp_PI_cfdp_request_copy_file_operation( const asn1SccCFDP_OPERATION_ID *, const asn1SccCFDP_FILE_PATH *, const asn1SccCFDP_CONFIG_DATA *, const asn1SccCFDP_FILE_PATH * );


void cfdp_PI_received_pdu( const asn1SccCFDP_DATA * );

/* Required interfaces */
extern void cfdp_RI_can_send( asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_cfdp_copy_file_operation_respond( const asn1SccCFDP_OPERATION_ID *, asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_error_callback( const asn1SccCFDP_ERROR_TYPE *, const asn1SccCFDP_ERROR_CODE * );


extern void cfdp_RI_get_file_size( const asn1SccCFDP_FILE_PATH *, asn1SccCFDP_SIZE * );


extern void cfdp_RI_indication_callback( const asn1SccCFDP_INDICATION_TYPE *, const asn1SccCFDP_TRANSACTION_ID * );


extern void cfdp_RI_list_directory( const asn1SccCFDP_FILE_PATH *, asn1SccCFDP_DATA *, asn1SccCFDP_SIZE *, asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_read_file( const asn1SccCFDP_FILE_PATH *, const asn1SccCFDP_OFFSET *, asn1SccCFDP_DATA *, const asn1SccCFDP_SIZE *, asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_send_pdu( const asn1SccCFDP_DATA *, asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_timer_restart( const asn1SccCFDP_TIMEOUT *, asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_timer_stop( asn1SccCFDP_BOOLEAN * );


extern void cfdp_RI_write_file( const asn1SccCFDP_FILE_PATH *, const asn1SccCFDP_OFFSET *, const asn1SccCFDP_DATA *, const asn1SccCFDP_SIZE *, asn1SccCFDP_BOOLEAN * );


#ifdef __cplusplus
}
#endif
