/* Body file for function bridge_b
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "bridge_b.h"
//#include <stdio.h>


void bridge_b_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[bridge_b] Startup");
}

void bridge_b_PI_error_callback
      (const asn1SccCFDP_ERROR_TYPE *IN_error_type,
       const asn1SccCFDP_ERROR_CODE *IN_error_code)

{
    asn1SccError_Info i;
    i.err_type = *IN_error_type;
    i.err_code = *IN_error_code;
    bridge_b_RI_err(&i);
}
