/* Body file for function test_function
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_function.h"
#include <stdio.h>
#include <unistd.h>
#include "string.h"

static bool is_done = false;

static bool file_exists(const char *fname)
{
	FILE *file;
	if ((file = fopen(fname, "r"))) {
		fclose(file);
		return true;
	}
	return false;
}

static int compare_files(const char *file1, const char *file2)
{
	FILE *fp1 = fopen(file1, "rb");
	FILE *fp2 = fopen(file2, "rb");

	if (!fp1 || !fp2) {
		if (fp1)
			fclose(fp1);
		if (fp2)
			fclose(fp2);
		return -1;
	}

	int result = 0;
	int ch1, ch2;

	while (1) {
		ch1 = fgetc(fp1);
		ch2 = fgetc(fp2);

		if (ch1 != ch2) {
			result = 1;
			break;
		}

		if (ch1 == EOF || ch2 == EOF)
			break;
	}

	if (ch1 != ch2)
		result = 1;

	fclose(fp1);
	fclose(fp2);
	return result;
}

void init_wrapper()
{
	const asn1SccCFDP_CONFIG_DATA entity_id = 6;
	const asn1SccCFDP_CHECKSUM_TYPE checksum_type = asn1SccCFDP_CHECKSUM_TYPE_modular;
	const asn1SccCFDP_CONFIG_DATA inactivity_time = 30;

	test_function_RI_cfdp_init(&entity_id, &checksum_type, &inactivity_time);
	test_function_RI_init_and_bind();
}


void test_function_startup(void)
{
}

void test_function_PI_trigger(void)
{
	// This part is used during test of file receive, it is executed during second program run
	// after test of source_file.txt send, test verification is done in python code
	if(file_exists("sent_target_file.txt")){
		if(is_done){
			return;
		}
	
		init_wrapper();
		is_done = true;
		return;
	}

	// This part is executed initialy, it tests file send
	init_wrapper();

	const asn1SccCFDP_OPERATION_ID operation_id = 10;
	asn1SccCFDP_BOOLEAN result;

	test_function_RI_cfdp_copy_operation_id_already_allocated(&operation_id, &result);

	if(result){
		printf("TEST FAILED\n");
		exit(EXIT_FAILURE);
	}

	asn1SccCFDP_FILE_PATH source_file_path;
	strcpy(source_file_path.field_data, "source_file.txt");
	asn1SccCFDP_CONFIG_DATA destination_id = 13;
	asn1SccCFDP_FILE_PATH target_file_path;
	strcpy(target_file_path.field_data, "sent_target_file.txt");

	test_function_RI_cfdp_request_copy_file_operation(&operation_id, &source_file_path, &destination_id, &target_file_path);

	sleep(2);
	test_function_RI_close_and_unbind();

	if (!file_exists("sent_target_file.txt")) {
		printf("TEST FAILED\n");
	    exit(EXIT_FAILURE);
	}

	if (compare_files("source_file.txt", "sent_target_file.txt") != 0) {
		printf("TEST FAILED\n");
	    exit(EXIT_FAILURE);
	}

	printf("SEND FILE TEST PASSED\n");
	exit(EXIT_SUCCESS);
}

void test_function_PI_cfdp_copy_file_operation_respond
      (const asn1SccCFDP_OPERATION_ID *IN_operation_id,
       asn1SccCFDP_BOOLEAN *OUT_result)

{
}


