/* Body file for function test_function
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_function.h"
//#include <stdio.h>


void test_function_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[test_function] Startup");
}

void test_function_PI_file_handling_copy_file_operation_respond
      (const asn1SccGAMMA_OPERATION_ID *IN_operation_id,
       const asn1SccROOT_REQUEST_ID *IN_request_id,
       const asn1SccROOT_TC_SECONDARY_HEADER *IN_secondary_header,
       asn1SccGAMMA_BOOLEAN *OUT_result)

{
   // Write your code here
}


void test_function_PI_trigger(void)
{
   // Write your code here
}


