TASTE-CFDP-DATAVIEW DEFINITIONS ::=
BEGIN

   GAMMA-CFDP-CONFIG-DATA ::= INTEGER (0 .. 4294967294)

   GAMMA-BOOLEAN ::= BOOLEAN

   GAMMA-FILE-PATH ::= SEQUENCE { field-data IA5String (SIZE(0..32)) }

   GAMMA-OPERATION-ID ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-DATA ::= SEQUENCE { field-data OCTET STRING (SIZE(0..512)) }

   GAMMA-CFDP-TIMEOUT ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-OFFSET ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-SIZE ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-CHECKSUM-TYPE ::= ENUMERATED {
        modular (0),
        none(15)
   }

   GAMMA-CFDP-CHECKSUM ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-INDICATION-TYPE ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-ERROR-CODE ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-ERROR-TYPE ::= INTEGER (0 .. 4294967294)

   GAMMA-CFDP-TRANSACTION-ID ::= SEQUENCE {
      source-entity-id INTEGER (0 .. 4294967294),
      seq-number INTEGER (0 .. 4294967294)
   }

ROOT-APPLICATION-PROCESS-ID ::= INTEGER(0..2047)
ROOT-PACKET-SEQUENCE-COUNT ::= INTEGER(0..16383)
ROOT-APPLICATION-PROCESS-USER-ID ::= INTEGER(0..65535)

ROOT-PACKET-VERSION-NUMBER ::= ENUMERATED {
   ccsds-packet (0)
}
ROOT-PACKET-TYPE ::= ENUMERATED {
   telemetry (0),
   telecommand (1)
}
ROOT-SECONDARY-HEADER-FLAG ::= BOOLEAN
ROOT-PACKET-ID ::= SEQUENCE {
   packet-type ROOT-PACKET-TYPE,
   secondary-header-flag ROOT-SECONDARY-HEADER-FLAG,
   application-process-id ROOT-APPLICATION-PROCESS-ID
}

ROOT-SEQUENCE-FLAGS ::= ENUMERATED {
   standalone-packet (3)
}
ROOT-PACKET-SEQUENCE-CONTROL ::= SEQUENCE {
   sequence-flags ROOT-SEQUENCE-FLAGS,
   packet-sequence-count ROOT-PACKET-SEQUENCE-COUNT
}
ROOT-REQUEST-ID ::= SEQUENCE {
   packet-version-number ROOT-PACKET-VERSION-NUMBER,
   packet-id ROOT-PACKET-ID,
   packet-sequence-control ROOT-PACKET-SEQUENCE-CONTROL
}

ROOT-TC-SECONDARY-HEADER ::= SEQUENCE {
   ack-successful-completion   BOOLEAN,
   ack-successful-progress     BOOLEAN,
   ack-successful-start        BOOLEAN,
   ack-successful-acceptance   BOOLEAN,
   source-id                   ROOT-APPLICATION-PROCESS-USER-ID
   -- spare user defined
}

END

