#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "cfdp_dataview.h"

enum MachineState {
	SEND_METADATA,
	SEND_FILE,
	SEND_EOF,
	TRANSACTION_CANCELLED,
	WAIT_FOR_MD,
	WAIT_FOR_EOF,
	GET_MISSING_DATA,
	SEND_FINISHED,
	COMPLETED
};

enum FaultHandlerAction {
	FAULT_HANDLER_CANCEL,
	FAULT_HANDLER_SUSPEND,
	FAULT_HANDLER_IGNORE,
	FAULT_HANDLER_ABANDON
};

enum IndicationType {
	TRANSACTION_INDICATION,
	EOF_SENT_INDICATION,
	FINISHED_INDICATION,
	REPORT_INDICATION,
	EOF_RECEIVED_INDICATION,
	METADATA_RECEIVED_INDICATION,
	FILESEGMENT_RECEIVED_INDICATION,
	ABANDONED_INDICATION,
	SUSPENDED_INDICATION,
	RESUMED_INDICATION,
	FAULT_INDICATION
};

enum ChecksumType { CHECKSUM_TYPE_MODULAR = 0, CHECKSUM_TYPE_NONE = 15 };

enum ErrorType { ASN1SCC_ERROR, UNSUPPORTED_ACTION, SEGMENTATION_ERROR };

#define DIRECTIVE_CODE_EOF 0x04
#define DIRECTIVE_CODE_FINISHED 0x05

#define MAX_FILE_NAME_SIZE (cfdpFileName_REQUIRED_BYTES_FOR_ACN_ENCODING - 1)
#define MAX_NUMBER_OF_SENDER_MACHINES 1
#define MAX_NUMBER_OF_RECEIVER_MACHINES 1

#define FILE_SEGMENT_LEN (cfdpFileData_REQUIRED_BYTES_FOR_ACN_ENCODING - 2)

extern const enum FaultHandlerAction DEFAULT_FAULT_HANDLER_ACTIONS[16];

#endif