#ifndef EVENT_H
#define EVENT_H

#include "transaction.h"

enum EventType {
	E0_ENTERED_STATE,
	E1_SEND_FILE_DATA,
	E2_ABANDON_TRANSACTION,
	E3_NOTICE_OF_CANCELLATION,
	E4_NOTICE_OF_SUSPENSION,
	E5_SUSPEND_TIMERS,
	E6_RESUME_TIMERS,

	E10_RECEIVED_METADATA,
	E11_RECEIVED_FILEDATA,
	E12_RECEIVED_EOF_NO_ERROR,
	E13_RECEIVED_EOF_CANCEL,
	E14_RECEIVED_ACK_EOF,
	E15_RECEIVED_NAK,
	E16_RECEIVED_FINISHED_NO_ERROR,
	E17_RECEIVED_FINISHED_CANCEL,
	E18_RECEIVED_ACK_FINISHED,

	E25_ACK_TIMEOUT,
	E26_NAK_TIMEOUT,
	E27_INACTIVITY_TIMEOUT,

	E30_RECEIVED_PUT_REQUEST,
	E31_RECEIVED_SUSPEND_REQUEST,
	E32_RECEIVED_RESUME_REQUEST,
	E33_RECEIVED_CANCEL_REQUEST,
	E34_RECEIVED_REPORT_REQUEST,

	E40_RECEIVED_FREEZE,
	E41_RECEIVED_THAW,
	E50_NOOP,
};

struct event {
	struct transaction transaction;
	enum EventType type;
};

#endif