/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <string.h>

typedef enum
{
    ISTATE_START,
    ISTATE_MEM_INITIALIZED,
    ISTATE_MEM_ERASED,
    ISTATE_MEM_PROXY_INITIALIZED,
    ISTATE_FILESYSTEM_INITIALIZED,
    ISTATE_FILE_TEST1_CREATED,
    ISTATE_FILE_TEST1_WRITTEN,
    ISTATE_FILE_TEST2_CREATED,
    ISTATE_FILE_TEST2_WRITTEN,
    ISTATE_CFDP_INITIALIZED,
    ISTATE_FILE_EXISTS,
    ISTATE_SEND_ABC_REQUESTED,
    ISTATE_SEND_TEST1_REQUESTED,
} InternalState;

static InternalState internal_state = ISTATE_START;
static bool fail = false;

static const asn1SccMEMORY_BLOCK_INDEX block_size = 8192; // 512 * 16
static const asn1SccT_UInt32 read_size = 16;
static const asn1SccT_UInt32 prog_size = 16;
static const asn1SccT_UInt32 block_count = 256; // 2097152 / 8192
static const asn1SccT_UInt32 block_cycles = 500;
static const asn1SccT_UInt32 cache_size = 16;
static const asn1SccT_UInt32 lookahead_size = 16;

static void dbg()
{
    asm volatile ("nop");
}

static void init_memory_access()
{
    asn1SccMemoryAccess_Result result;
    testfunction_RI_memoryaccess_init(&result);
    if(result) {
        internal_state = ISTATE_MEM_INITIALIZED;
    }
    else {
        fail = true;
        dbg();
    }
}

static void erase_memory_block()
{
    asn1SccMemoryAccess_Address address = 0x00400000u; // HARDCODED ADDRESS
    asn1SccMemoryAccess_Size size = block_size;
    asn1SccMemoryAccess_Result result = false;
    testfunction_RI_memory_erase(&address, &size, &result);
    if(result) {
        internal_state = ISTATE_MEM_ERASED;
    }
    else {
        fail = true;
        dbg();
    }
}
static void init_memory_access_proxy()
{
    asn1SccMEMORY_BLOCK_INDEX block_size_arg = block_size;
    testfunction_RI_memoryaccessproxy_init(&block_size_arg);
    internal_state = ISTATE_MEM_PROXY_INITIALIZED;
}


static void init_filesystem_access()
{
    asn1SccT_Boolean result = false;
    testfunction_RI_filesystem_init(&read_size, &prog_size, &block_size, &block_count, &block_cycles, &cache_size, &lookahead_size, &result);
    if(result) {
        internal_state = ISTATE_FILESYSTEM_INITIALIZED;
    } else {
        fail = true;
        dbg();
    }
}

static void create_file_test1()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "test1");
    asn1SccLITTLE_FS_MAXIMUM_SIZE maximum_size = 0;
    asn1SccLITTLE_FS_ADDITIONAL_FILE_ATTRIBUTE file_attr;
    file_attr.field_data.nCount = 1;
    file_attr.field_data.arr[0] = 0xab;
    asn1SccLITTLE_FS_BOOLEAN result = false;

    testfunction_RI_file_handling_create_file(&file_path, &maximum_size,
                                              &file_attr, &result);

    if (result) {
        internal_state = ISTATE_FILE_TEST1_CREATED;
    } else {
        fail = true;
        dbg();
    }
}

static void write_file_test1()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "test1");
    asn1SccLITTLE_FS_MEMORY_OFFSET memory_offset = 0;
    asn1SccLITTLE_FS_MEMORY_DATA memory_data;
    static const char* file_content = "Jupiter";
    strncpy(memory_data.field_data.arr, file_content, 128);
    memory_data.field_data.nCount = strlen(file_content);
    asn1SccLITTLE_FS_BOOLEAN result = false;

    testfunction_RI_write_to_file(&file_path, &memory_offset,
                                  &memory_data, &result);

    if (result) {
        internal_state = ISTATE_FILE_TEST1_WRITTEN;
    } else {
        fail = true;
        dbg();
    }
}


static void create_file_test2()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "test2");
    asn1SccLITTLE_FS_MAXIMUM_SIZE maximum_size = 0;
    asn1SccLITTLE_FS_ADDITIONAL_FILE_ATTRIBUTE file_attr;
    file_attr.field_data.nCount = 1;
    file_attr.field_data.arr[0] = 0xab;
    asn1SccLITTLE_FS_BOOLEAN result = false;

    testfunction_RI_file_handling_create_file(&file_path, &maximum_size,
                                              &file_attr, &result);

    if (result) {
        internal_state = ISTATE_FILE_TEST2_CREATED;
    } else {
        fail = true;
        dbg();
    }
}

static void write_file_test2()
{
    asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
    strcpy(file_path.field_data, "test2");
    asn1SccLITTLE_FS_MEMORY_OFFSET memory_offset = 0;
    asn1SccLITTLE_FS_MEMORY_DATA memory_data;
    static const char* file_content = "Saturn";
    strncpy(memory_data.field_data.arr, file_content, 128);
    memory_data.field_data.nCount = strlen(file_content);
    asn1SccLITTLE_FS_BOOLEAN result = false;

    testfunction_RI_write_to_file(&file_path, &memory_offset,
                                  &memory_data, &result);

    if (result) {
        internal_state = ISTATE_FILE_TEST2_WRITTEN;
    } else {
        fail = true;
        dbg();
    }
}

static void init_cfdp()
{
    const asn1SccCFDP_CONFIG_DATA entity_id = 6;
    const asn1SccCFDP_CHECKSUM_TYPE checksum_type = asn1SccCFDP_CHECKSUM_TYPE_modular;
    const asn1SccCFDP_CONFIG_DATA inactivity_time = 30;

    testfunction_RI_cfdp_init(&entity_id, &checksum_type, &inactivity_time);

    internal_state = ISTATE_CFDP_INITIALIZED;
}

static void init_finished()
{
    asm volatile ("nop");
}

static void send_abc_file()
{
    const asn1SccCFDP_OPERATION_ID operation_id = 1;
    asn1SccCFDP_BOOLEAN result;
    testfunction_RI_cfdp_copy_operation_id_already_allocated(&operation_id, &result);

    if(!result) {
        fail = true;
        dbg();
    }

    asn1SccCFDP_FILE_PATH source_file_path;
    strcpy(source_file_path.field_data, "abc");
    asn1SccCFDP_CONFIG_DATA destination_id = 5;
    asn1SccCFDP_FILE_PATH target_file_path;
    strcpy(target_file_path.field_data, "cba");
    testfunction_RI_cfdp_request_copy_file_operation(&operation_id, &source_file_path, &destination_id, &target_file_path);
    internal_state = ISTATE_SEND_ABC_REQUESTED;
}

static void testfunction_fileexsts(void) {
    send_abc_file();
}

static void testfunction_send_test1(void)
{
    const asn1SccCFDP_OPERATION_ID operation_id = 2;
    asn1SccCFDP_BOOLEAN result;
    testfunction_RI_cfdp_copy_operation_id_already_allocated(&operation_id, &result);

    if(!result) {
        fail = true;
        dbg();
    }

    asn1SccCFDP_FILE_PATH source_file_path;
    strcpy(source_file_path.field_data, "test1");
    asn1SccCFDP_CONFIG_DATA destination_id = 5;
    asn1SccCFDP_FILE_PATH target_file_path;
    strcpy(target_file_path.field_data, "test1");
    testfunction_RI_cfdp_request_copy_file_operation(&operation_id, &source_file_path, &destination_id, &target_file_path);
    internal_state = ISTATE_SEND_TEST1_REQUESTED;
}

void testfunction_startup(void)
{
}

void testfunction_PI_cfdp_copy_file_operation_respond
    (const asn1SccCFDP_OPERATION_ID *IN_operation_id,
     asn1SccCFDP_BOOLEAN *OUT_result)
{
    asm volatile ("nop");
    *OUT_result = true;
}

void testfunction_PI_trigger(void)
{
    if(fail) {
        return;
    }
    switch(internal_state) {
    case ISTATE_START:
        init_memory_access();
        break;
    case ISTATE_MEM_INITIALIZED:
        erase_memory_block();
        break;
    case ISTATE_MEM_ERASED:
        init_memory_access_proxy();
        break;
    case ISTATE_MEM_PROXY_INITIALIZED:
        init_filesystem_access();
        break;
    case ISTATE_FILESYSTEM_INITIALIZED:
        create_file_test1();
        break;
    case ISTATE_FILE_TEST1_CREATED:
        write_file_test1();
        break;
    case ISTATE_FILE_TEST1_WRITTEN:
        create_file_test2();
        break;
    case ISTATE_FILE_TEST2_CREATED:
        write_file_test2();
        break;
    case ISTATE_FILE_TEST2_WRITTEN:
        init_cfdp();
        break;
    case ISTATE_CFDP_INITIALIZED:
        init_finished();
        break;
    case ISTATE_FILE_EXISTS:
        send_abc_file();
        break;
    case ISTATE_SEND_ABC_REQUESTED:
        // do nothing, the other cyclic interface shall set next state
        break;
    case ISTATE_SEND_TEST1_REQUESTED:
        break;
    }
}

void testfunction_PI_test_trigger(void)
{    
    if(internal_state == ISTATE_CFDP_INITIALIZED) {
        asn1SccLITTLE_FS_REPOSITORY_PATH file_path;
        strcpy(file_path.field_data, "abc");
        asn1SccLITTLE_FS_MEMORY_OFFSET memory_offset = 0;
        asn1SccLITTLE_FS_MEMORY_OFFSET length = 3;
        asn1SccLITTLE_FS_MEMORY_DATA memory_data;
        memory_data.field_data.nCount = 0;
        asn1SccLITTLE_FS_BOOLEAN result = false;

        testfunction_RI_read_file(&file_path, &memory_offset, &length, &memory_data, &result);

        if(result) {
            if(memory_data.field_data.nCount == 3)
            {
                testfunction_fileexsts();
            }
        }
    }
    else if(internal_state == ISTATE_SEND_ABC_REQUESTED)
    {
        testfunction_send_test1();
    }
}

