/* Body file for function collector
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "collector.h"
//#include <stdio.h>

static volatile int bridge_sent_count = 0;

void collector_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[collector] Startup");
}

void collector_PI_send_pdu
      (const asn1SccCFDP_DATA *IN_pdu_data,
       asn1SccCFDP_BOOLEAN *OUT_result)

{
    collector_RI_send(IN_pdu_data);
    ++bridge_sent_count;

    *OUT_result = true;
}

void collector_PI_error_callback
    (const asn1SccCFDP_ERROR_TYPE *IN_error_type,
     const asn1SccCFDP_ERROR_CODE *IN_error_code)

{
    asn1SccError_Info i;
    i.err_type = *IN_error_type;
    i.err_code = *IN_error_code;
    collector_RI_err(&i);
}

void collector_PI_indication_callback
    (const asn1SccCFDP_INDICATION_TYPE *IN_indication_type,
     const asn1SccCFDP_TRANSACTION_ID *IN_transaction_id)

{
    asn1SccIndication_Info i;
    i.ind_type = *IN_indication_type;
    i.trans_id = *IN_transaction_id;
    collector_RI_indication(&i);
}
